"""remove is_disabled column from Member model

Revision ID: 0356eca89026
Revises: 0a4dde7f5882
Create Date: 2021-01-29 04:06:11.906479

"""
# pylint: disable=no-member
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0356eca89026'
down_revision = '0a4dde7f5882'
branch_labels = None
depends_on = None


def upgrade():
    # revised commands auto generated by Alembic
    # info on batch migrations: https://alembic.sqlalchemy.org/en/latest/batch.html
    with op.batch_alter_table('members') as batch_op:
        batch_op.drop_column('is_disabled')
    # end Alembic commands


def downgrade():
    # revised commands auto generated by Alembic
    with op.batch_alter_table('members') as batch_op:
        batch_op.add_column(sa.Column('is_disabled', sa.BOOLEAN(), nullable=True))
    # end Alembic commands
