"""add is_approved to Member model

Revision ID: 0a4dde7f5882
Revises: fb170604ca51
Create Date: 2021-01-29 03:42:13.185863

"""
# pylint: disable=no-member
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4dde7f5882'
down_revision = 'fb170604ca51'
branch_labels = None
depends_on = None


def upgrade():
    # revised commands auto generated by Alembic
    op.add_column('members', 
        sa.Column('is_approved', sa.Boolean(name='is_approved__bool'), nullable=True))
    # end Alembic commands


def downgrade():
    # revised commands auto generated by Alembic
    op.drop_column('members', 'is_approved')
    # end Alembic commands
