"""add is_superuser boolean field to User model

Revision ID: 51d5cbf55f4e
Revises: 1b665b3389db
Create Date: 2021-01-15 18:39:04.430368

"""
# pylint: disable=no-member
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d5cbf55f4e'
down_revision = '1b665b3389db'
branch_labels = None
depends_on = None


def upgrade():
    # adjusted commands auto generated by Alembic #
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(name='is_superuser__bool'), nullable=True))
    # end Alembic commands #


def downgrade():
    # adjusted commands auto generated by Alembic #
    op.drop_column('users', 'is_superuser')
    # end Alembic commands #
