"""rename is_deleted to is_disabled for users and members

Revision ID: dd97ea119cbc
Revises: 51d5cbf55f4e
Create Date: 2021-01-21 18:48:25.840045

"""
# pylint: disable=no-member
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd97ea119cbc'
down_revision = '51d5cbf55f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### adjusted commands auto generated by Alembic ###
    op.alter_column('users', 'is_deleted', new_column_name='is_disabled')
    op.alter_column('members', 'is_deleted', new_column_name='is_disabled')
    # ### end Alembic commands ###


def downgrade():
    # ### adjusted commands auto generated by Alembic ###
    op.alter_column('users', 'is_disabled', new_column_name='is_deleted')
    op.alter_column('members', 'is_disabled', new_column_name='is_deleted')
    # ### end Alembic commands ###
