"""add max_members to Group

Revision ID: fb170604ca51
Revises: dd97ea119cbc
Create Date: 2021-01-27 16:13:04.099833

"""
# pylint: disable=no-member
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb170604ca51'
down_revision = 'dd97ea119cbc'
branch_labels = None
depends_on = None


def upgrade():
    # revised commands auto generated by Alembic
    op.add_column('groups', sa.Column('max_members', sa.Integer(), nullable=True))
    # end Alembic commands


def downgrade():
    # revised commands auto generated by Alembic
    op.drop_column('groups', 'max_members')
    # end Alembic commands
