"""change invitation_code to password for Group

Revision ID: fe0b13ccda02
Revises: 0356eca89026
Create Date: 2021-01-30 00:43:58.185303

"""
# pylint: disable=no-member
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0b13ccda02'
down_revision = '0356eca89026'
branch_labels = None
depends_on = None


def upgrade():
    # revised commands auto generated by Alembic
    # note: before running with sqlite modify quizzz.db.set_sqlite_pragma:
    # set there "PRAGMA foreign_keys=off";
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=20), nullable=True))
        batch_op.drop_constraint('uq_groups_invitation_code', type_='unique')
        batch_op.drop_column('invitation_code')
    # end Alembic commands


def downgrade():
    # revised commands auto generated by Alembic
    # note: before running with sqlite modify quizzz.db.set_sqlite_pragma:
    # set there "PRAGMA foreign_keys=off";
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_code', sa.VARCHAR(length=10), nullable=True))
        batch_op.create_unique_constraint('uq_groups_invitation_code', ['invitation_code'])
        batch_op.drop_column('password')
    op.execute('UPDATE groups SET invitation_code=id')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('invitation_code', nullable=False)
    # end Alembic commands
