---
# Configuration for Ubuntu

- name: Configure Ubuntu
  hosts: webserver
  become: true
  gather_facts: no

  tasks:
  - name: Configure Firewall (Allow SSH) 
    ufw:
      rule: allow
      name: OpenSSH
    become: true

  - name: Configure Firewall (Allow HTTP/HTTPS)
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
      - 80
      - 443
    become: true

  - name: Make Sure Firewall Is Enabled
    ufw: 
      state: enabled
    become: true